name: release

on: push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: go build -o mpsfwd.x86-64
        working-directory: ./mpsfwd
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest files
          tag_name: latest
          files: |
            mpsfwd/mpsfwd.x86-64
